city_newsproject/city_newsproject/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls.static import static
from city_newsproject import settings

from newsapp.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newsapp.urls')),
    path('captcha/', include('captcha.urls')),
    path('forum/', include('forum_app.urls')),
    path('users/', include('users.urls', namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = pageNotFound

city_newsproject/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = "users"
 
urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/',
        PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
        name="password_change_done"),
]

city_newsproject/templates/base_project.html
{% load static %}
<!DOCTYPE html>

<html>
    <head>
        <title>{{title}}</title>
        <link type="text/css" href="{% static 'newsapp/css/styles.css' %}" rel="stylesheet" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <link rel="shortcut icon" href="{% static 'newsapp/images/main.ico' %}" type="image/x-icon"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    
    <div class="header">
        <ul id="mainmenu" class="mainmenu">
        <li class="logo"><a href="{% url 'home' %}"><div class="logo"></div></a></li>

        <li><a href="{% url 'home' %}">новости</a></li>
        <li><a href="{% url 'forum_home' %}">форум</a></li>


{% if request.user.is_authenticated %}
    <li class="last"> <a href="{% url 'users:profile' %}">{{user.username}}</a> | <a href="{% url 'users:logout' %}">Выйти</a></li>
{% else %}
    <li class="last"><a href="{% url 'users:register' %}">Регистрация</a> | <a href="{% url 'users:login' %}">Войти</a></li>
{% endif %}

        </ul>
        <div class="clear"></div>
    </div>


{% block app %}
{% endblock %}

</html>